# Generated by Django 3.0 on 2019-12-29 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='ip_rules_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='user',
            field=models.OneToOneField(help_text='Requests will be performed using this user', on_delete=django.db.models.deletion.CASCADE, related_name='consumer', to=settings.AUTH_USER_MODEL),
        ),
    ]
