# Generated by Django 3.0 on 2020-01-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0003_auto_20200105_1204'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['subject'], name='jwt_auth_to_subject_b97f77_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['audience'], name='jwt_auth_to_audienc_645332_idx'),
        ),
    ]
